branches:
  except:
  - dev
language: cpp
matrix:
  include:
  - name: linux-x64
    os: linux
    dist: bionic
    env: EXTRA_FLAGS='target_cpu="x64"'
  - name: osx
    os: osx
    osx_image: xcode11.3
addons:
  apt:
    packages:
    - ninja-build
    - pkg-config
    - libnss3-dev
    - qemu-user
  homebrew:
    packages:
    - ninja
    - ccache
cache:
  directories:
  - "$HOME/.ccache"
  - src/out/sysroot-build/openwrt
script:
- "./tools/import-upstream.sh"
- "( cd src; ./get-clang.sh )"
- ccache -s
- "( cd src; ./build.sh )"
- ccache -s
- "./tests/basic.sh src/out/Release/naive"
- export BUILD_NAME="naiveproxy-$TRAVIS_BRANCH-$TRAVIS_JOB_NAME"
- mkdir $BUILD_NAME
- cp src/out/Release/naive src/config.json LICENSE USAGE.txt $BUILD_NAME
- tar zcvf $BUILD_NAME.tar.gz $BUILD_NAME
deploy:
  provider: releases
  api_key:
    secure: B8isUJgk5Vy9KJp43KAuVslhbeP85ATCO/65QyqvoSSTG9ceCDRUmtoJZ5HPO1pQK7eIc23qcqRbjwWE723j0B16DrqOaHPnDrpzyBb7nH9Wp2QEI43oFN7SqxTK9uI8bxmTVvtuuPan8QHkYox2PWxTbAJ3BxYi0IUI8Rfb2btSsurvla3j+s8m46rE5kIs+w7NZBala9WQblk5+BXXY/kkZvLT6EMXlErC7pABCPEkwC2neaeCO6nYQof5h8E/znxt4TNP8n9iiaEA6vWx3xN7OFhPVtyd0aXfgOpV1JgGNylezniVug5lOaCzRpqCo8jsh3jzvet3E6WYXcB8WVO6vK6M4NILhPgua6cJOf52ih4pqOHJOFK0VjepUVqYJG/np71lm9zY/K4xZpo14QdicpoYtMX/qTiP6SKm5t4Uldt+iDpACqDzwD5Vf/vAuypAzZ706VWlQ1rgsJsHHuLIc+idt+sgpbC1cpWPp50+zmBZGhbqO/mv25Nwhx4ZM8btcWD5G3BnbpTOXE2elPtubnAuT7LViwb5bObRPI1zwAX+vs+RE46uYAHT+3EQHv8EQyu3+f2CFEAFfjm5KOQxMP3QALVn8EPPQzz7LjquxwHqU9mybvRk3kV57VmRtGeP3yu/KKZqT7ofhTwEv1WqjKwu0wpohm8jfs1Jws4=
  file: "$BUILD_NAME.tar.gz"
  on:
    tags: true
  skip_cleanup: 'true'
